V-01
ares909/carsharing-service pull request #1
Opened 2021-09-17 13:30 UTC by ares909

Сделаны задачи: V-01 & F-01
* Верстка без использования UI библиотек (т.к учусь - практикуюсь в верстке)
* Слайдер также сделан на кастомном хуке без использования библиотек. Цель была понять, как работает изнутри

2021-09-19 17:05 UTC, chugunovns21 requested changes

2021-09-19 17:05 UTC, chugunovns21 commented on src/components/Footer/Footer.jsx
> +export default Footer;
Думаю, лучше придерживаться современного синтаксиса и использовать стрелочные функции.

2021-09-19 17:05 UTC, chugunovns21 commented on src/components/Footer/Footer.scss
> +.footer {
А если такой класс нужно будет использовать где-то еще? Прочитай про CSS Modules и используй их.

2021-09-19 17:05 UTC, chugunovns21 commented on src/components/NavBar/NavBar.jsx
> +    );
В таких случаях лучше использовать оператор "switch" - он повышает читаемость кода, и если нужно будет добавить еще условия - в нем это будет сделать на много проще.

2021-09-19 17:05 UTC, chugunovns21 commented on src/components/PopupMenu/PopupMenu.jsx
> +        <section className={`popup-menu ${isOpened ? "popup-menu_active" : ""}`}>
Идея хорошая, но нужно поработать над реализацией. Прочитай про "classnames" и используй ее.

2021-09-19 17:05 UTC, chugunovns21 commented on src/constants/constants.js
> +
Лучше этот файл разложить на более конкретные.

2021-09-19 17:05 UTC, chugunovns21 commented on src/constants/constants.js
> +];
Это положить рядом со слайдером

2021-09-19 17:05 UTC, chugunovns21 commented on src/constants/constants.js
> +];
И это тоже перенести к месту использования

2021-09-19 17:05 UTC, chugunovns21 commented on src/hooks/useSlider.js
> +
Ну а это просто круто)

2021-09-19 17:05 UTC, chugunovns21 commented on src/components/Header/Header.jsx
> +import Button from "../UI/Button.jsx";
Обычно, порядок импорта такой:
1) Библиотеки
2) Компоненты
3) Картинки/Константы
4) Стили

2021-09-19 17:05 UTC, chugunovns21 commented on src/pages/MainPage/MainPage.jsx
> +                <Main isOpened={isOpened} toggle={toggle} />
На что влияет isOpened, который передается компоненту?
Он меняет класс, но класс ничего не изменяет.

2021-09-19 17:05 UTC, chugunovns21 commented on src/styles/index.css
> +}
Все стили в одном файле? У тебя уже вроде есть стили для слайдера в отдельной папке? И стили для popUp тоже в отдельном файле лежат. Подумай, как можно оптимизировать стили используя css modules, про которые я писал выше.

2021-09-21 06:48 UTC, ares909 commented on src/components/Footer/Footer.jsx
> +export default Footer;
изменил во всех файлах

2021-09-21 06:49 UTC, ares909 commented on src/components/Footer/Footer.scss
> +.footer {
Добавил css модули

2021-09-21 06:49 UTC, ares909 commented on src/components/NavBar/NavBar.jsx
> +    );
готово

2021-09-21 06:49 UTC, ares909 commented on src/components/PopupMenu/PopupMenu.jsx
> +        <section className={`popup-menu ${isOpened ? "popup-menu_active" : ""}`}>
Добавил условие с classnames

2021-09-21 06:50 UTC, ares909 commented on src/constants/constants.js
> +
готово, положил все картинки, слайды рядом с компонентами. Файл с константами оставил  (с тем что там осталось) на случай появления новых (тира api key и тд)

2021-09-21 06:50 UTC, ares909 commented on src/constants/constants.js
> +];
готово

2021-09-21 06:51 UTC, ares909 commented on src/hooks/useSlider.js
> +
Спасибо)

2021-09-21 06:53 UTC, ares909 commented on src/components/Header/Header.jsx
> +import Button from "../UI/Button.jsx";
готово

2021-09-21 06:53 UTC, ares909 commented on src/pages/MainPage/MainPage.jsx
> +                <Main isOpened={isOpened} toggle={toggle} />
убрал везде, кроме popup

2021-09-21 06:54 UTC, ares909 commented on src/styles/index.css
> +}
оставил в index.scss только шрифты и файл с миксинами, откуда они импортируются в модули

2021-09-21 07:02 UTC, ares909 commented
Комменты по верстке

1) С новым функционалом, будут добавлять все новые и новые компоненты. Думаю лучше добавить еще один уровень вложенности, например добавить папку mainPage и сложить туда все компоненты, которые используются только там.

Добавил папку mainPage в компонентах, сложил туда все то, что там используется. оставил снаружны те, которые попадут и на страницу  с формой

2)  Не корректно отображается контейнер в браузере

Поправил, теперь на любом разрешении контейнер по середине


3) Значок инсты не закрашен внутри
Исправлено

4) Неправильно перекрывается изображение (неправильно ведет себя на разных размерах экрана)
Исправлено

5)При таком разрешении должен все же более менее корректно отображаться мобильный вид
Испрвлено

6) Не по шаблону (так же посмотри поведение при наведении на язык)
Поменял как в шаблоне э

7) Стили текста не по макету, текст наезжает на управление
Исправлено

8) Если уж используем семантические тэги - то div можно заменить на main.
Вместо использования огромного margin у header, можно сделать весь контейнер - flex-column. И расположить элементы между. Тогда все встанет на свои места.

Готово

2021-09-21 07:35 UTC, chugunovns21 commented on src/constants/constants.js
> +
Правильно

2021-09-21 08:22 UTC, chugunovns21 requested changes

2021-09-21 08:22 UTC, chugunovns21 commented on src/components/App/App.jsx
> +};
Продолжаем изучать современный синтаксис)
const func = () => { return (</>) } можно заменить на
const func = () => ( </> )

2021-09-21 08:22 UTC, chugunovns21 commented on src/components/Header/Header.jsx
> +        <>
Зачем пустая разметка? Header же оборачивает все.

2021-09-21 08:22 UTC, chugunovns21 commented on src/hooks/useModal.js
> +    };
Измени функцию, как я описал выше

2021-09-21 08:22 UTC, chugunovns21 commented on src/pages/MainPage/MainPage.jsx
> +        <>
Пустой тэг...

2021-09-21 10:20 UTC, ares909 commented on src/components/Header/Header.jsx
> +        <>
убрал

2021-09-21 10:22 UTC, ares909 commented on src/components/App/App.jsx
> +};
заменил

2021-09-21 10:25 UTC, ares909 commented on src/hooks/useModal.js
> +    };
изменил

2021-09-21 10:25 UTC, ares909 commented on src/pages/MainPage/MainPage.jsx
> +        <>
убрал

2021-09-21 12:27 UTC, merged