V 02 & F 02
ares909/carsharing-service pull request #3
Opened 2021-10-06 12:34 UTC by ares909

Готовы задачи F2 и V2. 
Форма - React-hooks-form
Автокомплит - кастомный

2021-10-06 12:36 UTC, ares909 commented
Деплой https://ares909.github.io/carsharing-service/#/order

2021-10-07 16:45 UTC, chugunovns21 requested changes

2021-10-07 16:45 UTC, chugunovns21 commented on src/api/api.js
> +
Молодец) Все здорово оформил тут)

2021-10-07 16:45 UTC, chugunovns21 commented on src/components/Common/NavBar/NavButtons.jsx
> +// ];
Нужно удалять комменты. Или оставлять пояснения, если они будут дальше нужны

2021-10-07 16:45 UTC, chugunovns21 commented on src/components/MainPage/Main/Main.jsx
> +        e.preventDefault();
Какой эвент ты тут останавливаешь?

2021-10-07 16:45 UTC, chugunovns21 commented on src/components/OrderPage/LocationStep/LocationStep.jsx
> +    );
У тебя один и тот же контейнер будет отрисовываться на каждом шаге? Давай вынесем это в отдельный компонент.

2021-10-11 07:15 UTC, ares909 commented on src/api/api.js
> +
спасибо)

2021-10-11 07:16 UTC, ares909 commented on src/components/Common/NavBar/NavButtons.jsx
> +// ];
убрал

2021-10-11 07:16 UTC, ares909 commented on src/components/MainPage/Main/Main.jsx
> +        e.preventDefault();
никакой) убрал

2021-10-11 07:17 UTC, ares909 commented on src/components/OrderPage/LocationStep/LocationStep.jsx
> +    );
Готово. Добавил папку Common в OrderPage и добавил и туда Форму и Элемент с ее сабмитом

2021-10-14 17:34 UTC, chugunovns21 requested changes

2021-10-14 17:34 UTC, chugunovns21 commented on src/components/Common/Header/Header.jsx
> +                [`${styles.formHeader}`]: location.pathname !== "/",
Давай вот такие вещи будем выносить в константы, чтобы jsx не растягивать. У тебя ниже уже есть примеры такие.

2021-10-14 17:34 UTC, chugunovns21 commented on src/components/OrderPage/Common/FormSubmit/FormSubmit.jsx
> +    );
Если тернальник заменить на && - будет работать?

2021-10-14 17:34 UTC, chugunovns21 commented on src/components/OrderPage/LocationStep/LocationStep.jsx
> +    const dispatch = useDispatch();
Лучше объявлять в самом начале компонента, рядом с useSelect

2021-10-17 15:29 UTC, ares909 commented on src/components/OrderPage/LocationStep/LocationStep.jsx
> +    const dispatch = useDispatch();
поправил

2021-10-17 15:32 UTC, ares909 commented on src/components/OrderPage/Common/FormSubmit/FormSubmit.jsx
> +    );
будет)

2021-10-19 05:49 UTC, merged