V 03,04 && F-04,05
ares909/carsharing-service pull request #6
Opened 2021-10-23 07:53 UTC by ares909

Готовы шаги с выбором модели и выбором деталей заказа
Для календаря взял библиотечку react-datepicker и там были сложности со стилизацией, поэтому там не модуль scss а обычный импорт стилей.

2021-10-23 07:54 UTC, ares909 commented
Деплой https://ares909.github.io/carsharing-service/#/

2021-10-24 15:52 UTC, chugunovns21 requested changes

2021-10-24 15:52 UTC, chugunovns21 commented on src/components/Common/UI/Checkbox/Checkbox.jsx
> +                    value={props.value}
Ты же деструктуризировал выше, посмотри по всем компонентам

2021-10-24 15:52 UTC, chugunovns21 commented on src/components/Common/UI/Checkbox/Checkbox.jsx
> +        props.onChange();
Зачем эта обертка?

2021-10-24 15:52 UTC, chugunovns21 commented on src/components/Common/UI/Radio/Radio.jsx
> +        props.onChange(props.item);
Такую обертку делают, если тебе надо в функцию положить что-то из дочернего компонента, а тут ты прокидываешь туда те же пропсы. Нужно ли это делать тут?

2021-10-24 15:52 UTC, chugunovns21 commented on src/components/OrderPage/ModelStep/ModelStep.jsx
> +    const carsStatus = useSelector((state) => state.form.cars.status);
Вот тут ты намудрил

2021-10-28 17:11 UTC, ares909 commented on src/components/Common/UI/Checkbox/Checkbox.jsx
> +                    value={props.value}
поправил

2021-10-28 17:11 UTC, ares909 commented on src/components/Common/UI/Checkbox/Checkbox.jsx
> +        props.onChange();
убрал

2021-10-28 17:11 UTC, ares909 commented on src/components/Common/UI/Radio/Radio.jsx
> +        props.onChange(props.item);
убрал

2021-10-28 17:12 UTC, ares909 commented on src/components/OrderPage/ModelStep/ModelStep.jsx
> +    const carsStatus = useSelector((state) => state.form.cars.status);
почистил все вызовы useSelect

2021-10-31 18:04 UTC, chugunovns21 requested changes

2021-10-31 18:04 UTC, chugunovns21 commented on src/components/Common/NavBar/NavBar.jsx
> +                    {apiData.order.orderId && apiData.order.orderId !== "undefined" ? (
Нет ли тут ошибки в проверке, первая проверка всегда подразумевает "правдивость" второй

2021-10-31 18:04 UTC, chugunovns21 commented on src/components/Common/UI/Preloader/Preloader.jsx
> +};
Синтаксис стрелочных функций, я думал, ты уже запомнил это))

2021-10-31 18:04 UTC, chugunovns21 commented on src/components/OrderPage/Common/FormSubmit/FormSubmit.jsx
> +    const validationState = useSelector((state) => state.validation);
На счет селекторов вроде тоже уже обсуждали - внутренние колбэки выносятся в отдельный файл

2021-10-31 18:04 UTC, chugunovns21 commented on src/components/OrderPage/Common/OrderContainer/OrderContainer.jsx
> +    if (data !== "undefined" && data !== "") {
Чего ты добиваешься этой проверкой?

2021-10-31 18:04 UTC, chugunovns21 commented on src/components/OrderPage/Common/PriceContainer/PriceContainer.jsx
> +    const selectedCar = useSelector((state) => state.api.selectedCar);
Селектору тут не место, опять непонятно разделяешь логику. Почему ты тогда тут Price через селектор не получаешь? Давай car сделаем тоже пропсом

2021-10-31 18:04 UTC, chugunovns21 commented on src/components/OrderPage/Content/Content.jsx
> +        }
Тут можно if без фигурных скобок

2021-10-31 18:04 UTC, chugunovns21 commented on src/components/OrderPage/ExtraStep/ExtraStep.jsx
> +    const apiData = useSelector((state) => state.api);
Если ты много где будешь пользоваться конструкцией apiData.something - то лучше apiData сразу деструктуризировать

2021-10-31 18:04 UTC, chugunovns21 commented on src/components/OrderPage/ModelStep/ModelCard/ModelCard.jsx
> +    };
Опять делаешь ту же саму ошибку - в функцию из пропсов передаешь пропс. Это можно сделать в родительском компонентн

2021-10-31 18:04 UTC, chugunovns21 commented on src/hooks/useAutocomplete.js
> +            dispatch(resetApiCarExtra());
Можно ли это вынести в один экшн?

2021-11-01 05:27 UTC, ares909 commented on src/components/Common/NavBar/NavBar.jsx
> +                    {apiData.order.orderId && apiData.order.orderId !== "undefined" ? (
заменил на ||

2021-11-01 05:31 UTC, ares909 commented on src/components/Common/UI/Preloader/Preloader.jsx
> +};
поправил

2021-11-01 05:46 UTC, ares909 commented on src/components/OrderPage/Common/OrderContainer/OrderContainer.jsx
> +    if (data !== "undefined" && data !== "") {
Тут рендер компонента в зависимости от наличия данных для него. Вынес проверку наличия в formSubmit

2021-11-01 12:20 UTC, ares909 commented on src/components/OrderPage/ModelStep/ModelCard/ModelCard.jsx
> +    };
убрал

2021-11-01 12:21 UTC, ares909 commented on src/components/OrderPage/ExtraStep/ExtraStep.jsx
> +    const apiData = useSelector((state) => state.api);
вынес

2021-11-01 12:55 UTC, ares909 commented on src/components/OrderPage/Content/Content.jsx
> +        }
поправил

2021-11-01 15:05 UTC, ares909 commented on src/hooks/useAutocomplete.js
> +            dispatch(resetApiCarExtra());
сократил тут код

2021-11-03 06:24 UTC, merged